
DELETE FROM categories WHERE name IN (
  'CERVEJAS ANTARCTICA', 'CERVEJAS AMSTEL', 'CERVEJAS STELLA ARTOIS', 'CERVEJAS BECKS',
  'CERVEJAS HEINEKEN', 'CERVEJAS BUDWEISER', 'CERVEJAS SKOL', 'CERVEJAS BRAHMA',
  'CHOPP BARRIL', 'CERVEJAS DIVERSAS', 'DESTILADOS', 'ÁGUA/ÁGUA DE COCO/SUCOS',
  'ENERGÉTICOS', 'ISOTÔNICOS', 'REFRIGERANTES COCA-COLA', 'REFRIGERANTES ANTÁRCTICA',
  'REFRIGERANTES PEPSI', 'REFRIGERANTES DIVERSOS'
);
